# Generated by Django 5.1.2 on 2024-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup_app', '0002_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shape',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
